// react/src/components/SplitCard.jsx
import React, { useEffect } from "react";
import {
  createElement,
  loadAirwallex,
  getElement,
  confirmPaymentIntent,
} from "airwallex-payment-elements";

const intentid = "replace-with-your-intent-id";
const client_secret = "replace-with-your-client-secret";

const SplitCard = () => {
  useEffect(() => {
    loadAirwallex({
      env: "staging",
      origin: window.location.origin,
    }).then(() => {
      const cardNumEle = createElement("cardNumber");
      cardNumEle.mount("cardNumber");
      const cvcEle = createElement("cvc");
      cvcEle.mount("cvc");
      const expiryEle = createElement("expiry");
      expiryEle.mount("expiry");
    });

    const onReady = (event) => {
      /*
      ... Handle event
    */
      console.log(`Elements ready with ${JSON.stringify(event.detail)}`);
    };

    window.addEventListener("onReady", onReady);
    return () => {
      window.removeEventListener("onReady", onReady);
    };
  });

  const triggerConfirm = async () => {
    try {
      const cardNumEle = getElement("cardNumber");
      const confirmResult = await confirmPaymentIntent({
        element: cardNumEle,
        id: intentid,
        client_secret,
        payment_method_options: {
          card: {
            auto_capture: true,
          },
        },
      });
      console.log(`confirm success with ${JSON.stringify(confirmResult)}`);
    } catch (err) {
      console.log(`confirm fail with ${JSON.stringify(err)}`);
    }
  };

  return (
    <div>
      <h2>Option #4: Split Card element integration</h2>
      <div class="field-container">
        <div class="field-label">Card number</div>
        <div id="cardNumber" />
      </div>
      <div class="field-container">
        <div class="field-label">Expiry</div>
        <div id="expiry" />
      </div>
      <div class="field-container">
        <div class="field-label">Cvc</div>
        <div id="cvc" />
      </div>
      <button onClick={triggerConfirm}>Confirm</button>
    </div>
  );
};

export default SplitCard;

// angular/src/app/split-card/split-card.component.ts
import { Component, OnInit } from "@angular/core";
import {
  getElement,
  confirmPaymentIntent,
  createElement,
  loadAirwallex,
} from "airwallex-payment-elements";

const intentid = "replace-with-your-intent-id";
const client_secret = "replace-with-your-client-secret";

@Component({
  selector: "app-split-card",
  templateUrl: "./split-card.component.html",
})
export class SplitCardComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    loadAirwallex({
      env: "staging",
      origin: window.location.origin,
    }).then(() => {
      const cardNumEle = createElement("cardNumber");
      cardNumEle?.mount("cardNumber");
      const cvcEle = createElement("cvc");
      cvcEle?.mount("cvc");
      const expiryEle = createElement("expiry");
      expiryEle?.mount("expiry");
    });
    window.addEventListener("onSuccess", this.onSuccess);
  }

  ngOnDestroy(): void {
    window.removeEventListener("onSuccess", this.onSuccess);
  }

  onSuccess(event: any) {
    console.log(`Confirm success with ${JSON.stringify(event.detail)}`);
  }

  triggerConfirm = async () => {
    try {
      const cardNumEle = getElement("cardNumber");
      const confirmResult = await confirmPaymentIntent({
        element: cardNumEle!,
        id: intentid,
        client_secret,
        payment_method_options: {
          card: {
            auto_capture: true,
          },
        },
      });
      console.log(`confirm success with ${JSON.stringify(confirmResult)}`);
    } catch (err) {
      console.log(`confirm fail with ${JSON.stringify(err)}`);
    }
  };
}
