// vue/src/components/Card.vue
<template>
  <div class="card">
    <h1>{{msg}}</h1>
    <!-- HPP -->
    <h2>{{desc}}</h2>
    <div id='card'></div>
  </div>
</template>

<script>
import {createElement, loadAirwallex} from 'airwallex-payment-elements';

const client_secret = 'eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTk0NzIwMDEsImV4cCI6MTU5OTQ3NTYwMSwiYWNjb3VudF9pZCI6IjM0OWZhYWQ5LTYzZGEtNDg3MS05YTVhLWIyYTIxNjViNTNiNiIsImRhdGFfY2VudGVyX3JlZ2lvbiI6IlVLIiwiaW50ZW50X2lkIjoiaW50XzRGa3NsVWUwenJ4VkdtNDBDeklZd3g4TW9zaCJ9.cpM2hbhcFTubk4gqsXFUYB_FerIvjXjMcZGWDVbic98';
const intentid = 'int_4FkslUe0zrxVGm40CzIYwx8Mosh';

console.log(loadAirwallex);
loadAirwallex({
  env: 'staging', // 'staging' | 'demo' | 'prod'
  origin: window.location.origin
}).then(() => {
  const card = createElement('card', {
    intent: {
      id: intentid,
      client_secret: client_secret
    },
    component: 'default',
    autoCapture: true,
    withBilling: true
  });
  card.mount('card');

  // window.addEventListener('onSuccess', (event) => {
  //   console.log(JSON.stringify(event));
  // });
})

export default {
  name: 'Card',
  data () {
    return {
      msg: 'Airwallex checkout integration',
      desc: 'Option #3: Card integration'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
body {
  font-family: 'Helvetica Neue', Arial, sans-serif;
  color: #333;
  font-weight: 300;
}
h1 {
  text-align: center;
}
h2 {
  padding-top: 24px;
}
label {
  padding: 12px;
  display: block;
}
div {
  padding: 12px;
}
</style>

// typescript/src/components/card.tsx
import { useEffect } from 'react';
import {
  createElement,
  loadAirwallex,
  getElement,
  confirmPaymentIntent,
  ElementType
} from 'airwallex-payment-elements';

const intentId = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';
const ELEMENT_TYPE: ElementType = 'card';

const Index: React.FC = () => {
  useEffect(() => {
    loadAirwallex({
      env: "staging",
      origin: window.location.origin,
    }).then(() => {
      createElement(ELEMENT_TYPE)?.mount(ELEMENT_TYPE);
    });

    const onReady = (event: CustomEvent) => {
      /*
      ... Handle event
    */
      console.log(`Elements ready with ${JSON.stringify(event.detail)}`);
    };

    window.addEventListener('onReady', onReady as EventListener);
    return () => {
      window.removeEventListener('onReady', onReady as EventListener);
    };
  });

  const triggerConfirm = async () => {
    try {
      const cardNumberElement = getElement('card');
      if (cardNumberElement) {
        const confirmResult = await confirmPaymentIntent({
          element: cardNumberElement,
          id: intentId,
          client_secret,
          payment_method_options: {
            card: {
              auto_capture: true,
            },
          },
        });
        console.log(`confirm success with ${JSON.stringify(confirmResult)}`);
      }
    } catch (err) {
      console.log(`confirm fail with ${JSON.stringify(err)}`);
    }
  };

  return (
    <div>
      <h2>Option #6: Card element integration</h2>
      <div id={ELEMENT_TYPE} />
      <button onClick={triggerConfirm} style={{marginTop: '8px'}}>Confirm</button>
    </div>
  );
};

export default Index;
