// integrations/angular/src/app/split-card/split-card.component.ts
/**
 * split-card.component.ts
 * Airwallex Payment Demo - Angular.  Created by Roy Yang and Josie Ku.
 *
 * airwallex-payment-elements Split Card element integration in Angular
 * Comments with "Example" demonstrate how states can be integrated with the
 * element, they can be removed.
 *
 * Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/splitcard.md
 */

import { Component, OnInit } from '@angular/core';
// STEP #1: At the start of your file, import airwallex-payment-elements package
import {
  getElement,
  confirmPaymentIntent,
  createElement,
  loadAirwallex,
  EventDetail,
} from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

@Component({
  selector: 'app-split-card',
  templateUrl: './split-card.component.html',
  styles: [
    // Example: Custom styling for the inputs
    '#cardNumber,#cvc,#expiry { border: 1px solid; border-radius: 5px; padding: 5px 10px; margin-top: 8px; height: 28px }',
  ],
})
export class SplitCardComponent implements OnInit {
  // Example: element ready states, controls the display for when elements are successfully mounted
  cardNumberReady: boolean;
  cvcReady: boolean;
  expiryReady: boolean;
  // Example: element validation state, checks if each field is completed by the shopper
  cardNumberComplete: boolean;
  cvcComplete: boolean;
  expiryComplete: boolean;
  fieldsCompleted: boolean;
  // Example: controls submission state
  isSubmitting: boolean;
  // Example: set error state
  errorMessage: string;
  constructor() {
    this.cardNumberReady = this.cvcReady = this.expiryReady = false;
    this.cardNumberComplete = this.cvcComplete = this.expiryComplete = false;
    this.isSubmitting = false;
    this.fieldsCompleted = false;
    this.errorMessage = '';
    this.onReady = this.onReady.bind(this);
    this.onChange = this.onChange.bind(this);
    this.onBlur = this.onBlur.bind(this);
    this.onFocus = this.onFocus.bind(this);
    this.triggerConfirm = this.triggerConfirm.bind(this);
  }

  ngOnInit(): void {
    // STEP #2: Initialize Airwallex on mount with the appropriate production environment and other configurations
    loadAirwallex({
      env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
      origin: window.location.origin, // Setup your event target to receive the browser events message
      fonts: [
        // Customizes the font for the payment elements
        {
          src:
            'https://checkout.airwallex.com/fonts/CircularXXWeb/CircularXXWeb-Regular.woff2',
          family: 'AxLLCircular',
          weight: 400,
        },
      ],
      // For more detailed documentation at https://github.com/airwallex/airwallex-payment-demo/tree/master/docs#loadAirwallex
    }).then(() => {
      // STEP #4, 5: Create and mount the individual card elements
      createElement('cardNumber')?.mount('cardNumber'); // This 'cardNumber' id MUST MATCH the id on your cardNumber empty container created in Step 3
      createElement('cvc')?.mount('cvc'); // Same as above
      createElement('expiry')?.mount('expiry'); // Same as above
    });
    window.addEventListener('onReady', this.onReady);
    window.addEventListener('onChange', this.onChange);
    window.addEventListener('onBlur', this.onBlur);
    window.addEventListener('onFocus', this.onFocus);
  }

  // STEP #7: Add an event handler to ensure the element is mounted
  onReady = (event: any): void => {
    const { type } = event.detail as EventDetail;
    if (type === 'cardNumber') {
      this.cardNumberReady = true;
    }
    if (type === 'cvc') {
      this.cvcReady = true;
    }
    if (type === 'expiry') {
      this.expiryReady = true;
    }
  };

  // STEP #8: Add an event listener to listen to the changes in each of the input fields
  onChange = (event: any) => {
    const { type, complete } = event.detail as EventDetail;
    if (type === 'cardNumber') {
      this.cardNumberComplete = complete ?? false;
    }
    if (type === 'cvc') {
      this.cvcComplete = complete ?? false;
    }
    if (type === 'expiry') {
      this.expiryComplete = complete ?? false;
    }

    this.fieldsCompleted =
      this.cardNumberComplete && this.cvcComplete && this.expiryComplete; // Example: set button disabled state
  };

  // STEP #9: Add an event listener to get input focus status
  onFocus = (event: any): void => {
    const { type } = event.detail;
    // Customize your input focus style by listen onFocus event
    const element = document.getElementById(`${type}-error`);
    if (element) {
      element.innerHTML = ''; // Example: clear input error message
    }
  };

  // STEP #10: Add an event listener to show input error message when finish typing
  onBlur = (event: any): void => {
    const { error, type } = event.detail;
    const element = document.getElementById(`${type}-error`);
    if (element) {
      element.innerHTML = error?.message ?? JSON.stringify(error); // Example: set input error message
    }
  };

  // STEP #6a: Add a button handler to trigger the payment request
  triggerConfirm = async () => {
    this.isSubmitting = true; // Example: set button disabled state to prevent resubmission
    const cardNumber = getElement('cardNumber');
    if (cardNumber) {
      confirmPaymentIntent({
        element: cardNumber, // Only need to submit CardNumber element
        id: intent_id,
        client_secret,
        // Add other payment confirmation details, see docs here: https://github.com/airwallex/airwallex-payment-demo/tree/master/docs
        payment_method_options: {
          card: {
            auto_capture: true,
          },
        },
      })
        // STEP #6b: Listen to the request response
        .then((response) => {
          /**
           * ... Handle event on success
           */
          this.isSubmitting = false;
          window.alert(`Confirm success with ${JSON.stringify(response)}`);
        })
        // STEP #6c: Listen to errors
        .catch((error) => {
          /**
           * ... Handle event on error
           */
          this.isSubmitting = false;
          this.errorMessage = error.message ?? JSON.stringify(error); // Example: set error message
          console.error('There was an error', error);
        });
    }
  };

  OnDestroy(): void {
    window.removeEventListener('onReady', this.onReady);
    window.removeEventListener('onChange', this.onChange);
  }
}

<!-- 
  split-card.component.html
  Airwallex Payment Demo - Angular.  Created by Roy Yang and Josie Ku.

  This file is the html template for the Split Card component.
 -->
<div>
  <h2>Split Card element integration</h2>
  <!-- Styling example below: show loading state -->
  <p [style.display]="
      this.cardNumberReady && this.cvcReady && this.expiryReady
        ? 'none'
        : 'block'
    ">
    Loading...
  </p>
  <!-- Styling example below: show error message -->
  <p id="error" [style.display]="this.errorMessage.length > 0 ? 'block' : 'none'">
    {{ errorMessage }}
  </p>
  <!-- Styling example below: only displays block when all elements are ready  -->
  <div [style.display]="
      this.cardNumberReady && this.cvcReady && this.expiryReady
        ? 'block'
        : 'none'
    ">
    <!-- 
      STEP #3a: Add an empty container for the split card elements to be placed into
      - Ensure these are the only elements in your document with these id, otherwise 
        the elements may fail to mount. 
    -->
    <div class="field-container">
      <div class="field-label">Card number</div>
      <div id="cardNumber"></div>
      <p id="cardNumber-error" style="color: red"></p>
    </div>
    <div class="field-container">
      <div class="field-label">Expiry</div>
      <div id="expiry"></div>
      <p id="expiry-error" style="color: red"></p>
    </div>
    <div class="field-container">
      <div class="field-label">Cvc</div>
      <div id="cvc"></div>
      <p id="cvc-error" style="color: red"></p>
    </div>
    <!-- STEP #3b: Add a submit button to trigger the payment request -->
    <button on-click="triggerConfirm()" [disabled]="!fieldsCompleted || isSubmitting">
      <!-- [disabled] prevents incomplete submissions-->
      <span *ngIf="!isSubmitting">Confirm</span>
      <span *ngIf="isSubmitting">Submitting...</span>
    </button>
  </div>
</div>

// integrations/vue/src/components/splitCard.vue
<!--
  splitCard.vue
  Airwallex Payment Demo - Vue.  Created by Chao Ding and Josie Ku.

  airwallex-payment-elements Split Card element integration in Vue.
  Comments with "Example" demonstrate how states can be integrated
  with the element, they can be removed.

  Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/splitcard.md
-->
<template>
  <div>
    <h2>Split Card element integration</h2>
    <!-- Styling example below: show loading state when element is not ready -->
    <p id="loading">
      Loading...
    </p>
    <!-- Example: response message container -->
    <p id="error" style="display:none" />
    <div id="card-container" :style="{ display: 'none' }">
      <!-- 
        STEP #3a: Add empty containers for the split elements to be injected into 
        - Ensure these are the only elements in your document with these id, otherwise the elements may fail to mount.
      -->
      <div class="field-container">
        <div class="field-label">
          Card number
        </div>
        <div id="cardNumber" />
        <p id="cardNumber-error" :style="{ color: 'red' }" />
      </div>
      <div class="field-container">
        <div class="field-label">
          Expiry
        </div>
        <div id="expiry" />
        <p id="expiry-error" :style="{ color: 'red' }" />
      </div>
      <div class="field-container">
        <div class="field-label">
          Cvc
        </div>
        <div id="cvc" />
        <p id="cvc-error" :style="{ color: 'red' }" />
      </div>
      <!-- STEP #3b: Add a submit button to trigger the payment request -->
      <button id="confirm" :disabled="true" @click="triggerConfirm()">
        Confirm
      </button>
    </div>
  </div>
</template>

<script>
// STEP #1: Import airwallex-payment-elements package
import { createElement, confirmPaymentIntent, loadAirwallex, getElement } from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

const init = () => {
  // STEP #2: Initialize Airwallex on mount with the appropriate production environment and other configurations
  loadAirwallex({
    env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
    origin: window.location.origin, // Setup your event target to receive the browser events message
    fonts: [
      // Customizes the font for the payment elements
      {
        src: 'https://checkout.airwallex.com/fonts/CircularXXWeb/CircularXXWeb-Regular.woff2',
        family: 'AxLLCircular',
        weight: 400,
      },
    ],
    // For more detailed documentation at https://github.com/airwallex/airwallex-payment-demo/tree/master/docs#loadAirwallex
  }).then(() => {
    // STEP #4: Create and mount the individual card elements
    const cardNumEle = createElement('cardNumber');
    const cvcEle = createElement('cvc');
    const expiryEle = createElement('expiry');

    // STEP #5: Mount split card elements
    cardNumEle.mount('cardNumber'); // This 'cardNumber' id MUST MATCH the id on your cardNumber empty container created in Step 3
    cvcEle.mount('cvc'); // Same as above
    expiryEle.mount('expiry'); // Same as above
  });
};

// Set up local variable to check all elements are mounted
const elementsReady = {
  cardNumber: false,
  expiry: false,
  cvc: false,
};

// STEP #7: Add an event handler to ensure the element is mounted
const onReady = (event) => {
  const { type } = event.detail;
  if (elementsReady.hasOwnProperty(type)) {
    elementsReady[type] = true; // Set element ready state
  }

  if (!Object.values(elementsReady).includes(false)) {
    document.getElementById('loading').style.display = 'none'; // Example: hide loading state when element is mounted
    document.getElementById('card-container').style.display = 'block'; // Example: show element when mounted
  }
};

// Set up local variable to validate element inputs
const elementsCompleted = {
  cardNumber: false,
  expiry: false,
  cvc: false,
};

// STEP #8: Add an event listener to listen to the changes in each of the input fields
const onChange = (event) => {
  const { type, complete } = event.detail;
  if (elementsCompleted.hasOwnProperty(type)) {
    elementsCompleted[type] = complete; // Set element completion state
  }

  // Check if all elements are completed, and set submit button disabled state
  const allElementsCompleted = !Object.values(elementsCompleted).includes(false);
  document.getElementById('confirm').disabled = !allElementsCompleted;
};

// STEP #9: Add an event listener to handle events when there is an error
const onError = (event) => {
  /*
    ... Handle event on error
  */
  const { error } = event.detail;
  document.getElementById('error').style.display = 'block'; // Example: show error block
  document.getElementById('error').innerHTML = error.message; // Example: set error message
  console.log('There was an error', event.detail.error);
};

// STEP #10: Add an event listener to get input focus status
const onFocus = (event) => {
  const { type } = event.detail;
  const element = document.getElementById(`${type}-error`);
  if (element) {
    element.innerHTML = ''; // Example: clear input error message
  }
  // Customize your input focus style by listen onFocus event
};

// STEP #11: Add an event listener to show input error message when finish typing
const onBlur = (event) => {
  const { error, type } = event.detail;
  const element = document.getElementById(`${type}-error`);
  if (element) {
    element.innerHTML = error.message || JSON.stringify(error); // Example: set input error message
  }
};

// STEP #6a: Add a button handler to trigger the payment request
const triggerConfirm = async () => {
  const cardNumElement = getElement('cardNumber');
  confirmPaymentIntent({
    element: cardNumElement, // Only need to submit CardNumber element
    id: intent_id,
    client_secret,
    // Add other payment confirmation details, see docs here: https://github.com/airwallex/airwallex-payment-demo/tree/master/docs
    payment_method_options: {
      card: {
        auto_capture: true,
      },
    },
  })
    // STEP #6b: Listen to the request response
    .then((response) => {
      /**
       * ... Handle event on success
       */
      window.alert(`Confirm success with ${JSON.stringify(response)}`);
    })
    // STEP #6c: Listen to errors
    .catch((error) => {
      /**
       * ... Handle event on error
       */
      document.getElementById('error').style.display = 'block'; // Example: show error block
      document.getElementById('error').innerHTML = error.message; // Example: set error message
      console.error('There was an error', error);
    });
};

export default {
  name: 'CardEle',
  data() {
    return {
      triggerConfirm,
    };
  },
  mounted() {
    init();
    window.addEventListener('onReady', onReady);
    window.addEventListener('onChange', onChange);
    window.addEventListener('onError', onError);
    window.addEventListener('onFocus', onFocus);
    window.addEventListener('onBlur', onBlur);
  },
  beforeDestroy() {
    // Be sure to clean up event listeners when component unmounts
    window.removeEventListener('onReady', onReady);
    window.removeEventListener('onChange', onChange);
    window.removeEventListener('onError', onError);
    window.removeEventListener('onFocus', onFocus);
    window.removeEventListener('onBlur', onBlur);
  },
};
</script>

<style>
.field-container {
  margin: 0 auto 16px;
  width: 300px;
}
.field-container div {
  border: 1px solid;
  padding: 4px 8px;
  margin-top: 8px;
}
div.field-label {
  text-align: left;
  border: 0;
}

/* Custom styling for the inputs */
#cardNumber,
#cvc,
#expiry {
  border: 1px solid;
  border-radius: 5px;
  padding: 5px 10px;
  margin-top: 8px;
  height: 28px;
}
</style>
