// integrations@deprecated/angular/src/app/card/card.component.ts
/**
 * card.component.ts
 * Airwallex Payment Demo - Angular.  Created by Josie Ku.
 *
 * airwallex-payment-elements Card element integration in Angular
 * Comments with "Example" demonstrate how states can be integrated
 * with the element, they can be removed.
 *
 * Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/dropin.md
 */

import { Component, OnInit } from '@angular/core';
// STEP #1: At the start of your file, import airwallex-payment-elements package
import {
  createElement,
  loadAirwallex,
  ElementType,
  getElement,
  confirmPaymentIntent,
} from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styles: [
    // Example: Custom styling for card container
    '#card { border: 1px solid; border-radius: 5px; padding: 5px 10px; margin-top: 8px; height: 28px; width: 300px; }',
  ],
})
export class CardComponent implements OnInit {
  loading: boolean;
  isSubmitting: boolean;
  errorMessage: string;
  inputErrorMessage: string;
  domElement?: HTMLElement | null;
  constructor() {
    this.loading = true;
    this.isSubmitting = false;
    this.errorMessage = '';
    this.inputErrorMessage = '';
    this.onReady = this.onReady.bind(this);
    this.onError = this.onError.bind(this);
    this.onBlur = this.onBlur.bind(this);
    this.onFocus = this.onFocus.bind(this);
    this.domElement = null;
    this.triggerConfirm = this.triggerConfirm.bind(this);
  }

  ngOnInit(): void {
    // STEP #2: Initialize Airwallex on mount with the appropriate production environment and other configurations
    loadAirwallex({
      env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
      origin: window.location.origin, // Setup your event target to receive the browser events message
      // For more detailed documentation at https://github.com/airwallex/airwallex-payment-demo/tree/master/docs#loadAirwallex
    }).then(() => {
      // STEP #4, #5: Create and mount the card element
      this.domElement = createElement('card' as ElementType)?.mount('card'); // This 'card' id MUST MATCH the id on your empty container created in Step 3
      this.domElement?.addEventListener('onReady', this.onReady);
      this.domElement?.addEventListener('onError', this.onError);
      this.domElement?.addEventListener('onBlur', this.onBlur);
      this.domElement?.addEventListener('onFocus', this.onFocus);
    });
  }

  // STEP #7: Add an event listener to ensure the element is mounted
  onReady = (event: any): void => {
    /**
     * ... Handle event when elements are mounted
     */
    this.loading = false; // Example: set loading state
    console.log(`Elements ready with ${JSON.stringify(event.detail)}`);
  };

  // STEP #8: Add an event listener to respond to errors
  onError = (event: any): void => {
    /**
     * ... Handle events on error
     */
    const { error } = event.detail;
    this.errorMessage = error.message ?? JSON.stringify(error); // Example: set error message
    console.error('There was an error', error);
  };

  // STEP #9: Add an event listener to get input focus status
  onFocus = (event: any): void => {
    // Customize your input focus style by listen onFocus event
    this.inputErrorMessage = '';
  };

  // STEP #10: Add an event listener to show input error message when finish typing
  onBlur = (event: any): void => {
    const { error } = event.detail;
    this.inputErrorMessage = error?.message ?? JSON.stringify(error); // Example: set input error message
  };

  // STEP #6a: Add a button handler to trigger the payment request
  triggerConfirm = (): void => {
    this.isSubmitting = true;
    const card = getElement('card');
    if (card) {
      confirmPaymentIntent({
        element: card,
        id: intent_id,
        client_secret,
        // Add other payment confirmation details, see docs here: https://github.com/airwallex/airwallex-payment-demo/tree/master/docs
        payment_method_options: {
          card: {
            auto_capture: true,
          },
        },
      })
        // STEP #6b: Listen to the request success response
        .then((response) => {
          /**
           * ...Handle confirm response
           */
          this.isSubmitting = false; // Example: sets loading state
          window.alert(`Payment Intent confirmation was successful: ${JSON.stringify(response)}`);
        })
        // STEP #6c: Listen to the request failure response
        .catch((error) => {
          /**
           * ... Handle error response
           */
          this.isSubmitting = false; // Example: sets loading state
          this.errorMessage = error.message ?? JSON.stringify(error); // Example: set error message
          console.error('There was an error', error);
        });
    }
  };

  OnDestroy(): void {
    // Clean up listeners when the component is unmounting
    this.domElement?.removeEventListener('onReady', this.onReady);
    this.domElement?.removeEventListener('onError', this.onError);
  }
}

<!-- 
  card.component.html
  Airwallex Payment Demo - Angular.  Created by Josie Ku.

  This file is the html template for the Card component.
 -->
<div>
  <h2>Card integration</h2>
  <!-- Styling example below: show loading state -->
  <p [style.display]="this.loading ? 'block' : 'none'">Loading...</p>
  <!-- Styling example below: show error message -->
  <p id="error" [style.display]="this.errorMessage.length > 0 ? 'block' : 'none'">
    {{ errorMessage }}
  </p>
  <!-- Styling example below: only show field if element is ready -->
  <div class="field-container" [style.display]="!this.loading ? 'block' : 'none'">
    <!-- 
      STEP #3a: Add an empty container for the card element to be placed into
      - Ensure this is the only element in your document with this id, otherwise 
        the element may fail to mount. 
    -->
    <div id="card"></div>
    <p style="color: red">{{ inputErrorMessage }}</p>
    <!-- STEP #3b: Add a submit button to trigger the payment request -->
    <button on-click="triggerConfirm()" [disabled]="isSubmitting">
      <!-- [disabled] prevents incomplete submissions-->
      <span *ngIf="!this.isSubmitting">Confirm</span>
      <span *ngIf="this.isSubmitting">Submitting...</span>
    </button>
  </div>
</div>

// integrations@deprecated/react/src/components/Card.jsx
/**
 * Card.jsx
 * Airwallex Payment Demo - React.  Created by Josie Ku.
 *
 * airwallex-payment-elements Card element integration in React.js
 * Comments with "Example" demonstrate how states can be integrated
 * with the element, they can be removed.
 *
 * Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/card.md
 */

import React, { useEffect, useState } from 'react';
// STEP #1: At the start of your file, import airwallex-payment-elements package
import { createElement, loadAirwallex, confirmPaymentIntent, getElement } from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

const Card = () => {
  const [elementShow, setElementShow] = useState(false); // Example: show element state
  const [isSubmitting, setIsSubmitting] = useState(false); // Example: show submission processing state
  const [errorMessage, setErrorMessage] = useState(false); // Example: set error state
  const [inputErrorMessage, setInputErrorMessage] = useState(false); //  Example: set input error state
  useEffect(() => {
    // STEP #2: Initialize Airwallex with the appropriate Airwallex environment and other configurations
    loadAirwallex({
      env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
      origin: window.location.origin, // Setup your event target to receive the browser events message
      // For more detailed documentation at https://github.com/airwallex/airwallex-payment-demo/tree/master/docs
    }).then(() => {
      // STEP #4: Create the card element
      const card = createElement('card');
      // STEP #5: Mount the card element to the empty container created previously
      card.mount('card'); // This 'card' id MUST MATCH the id on your empty container created in Step 3
    });

    // STEP #7: Add an event listener to ensure the element is mounted
    const onReady = (event) => {
      /**
       * ...Handle events on element ready
       */
      setElementShow(true); // Example: sets show once mounted
      getElement('card').focus(); // Example: focuses on input field
      console.log(`The Card element is ready, ${JSON.stringify(event.detail)}`);
    };

    // STEP #8: Add an event listener to respond to errors
    const onError = (event) => {
      /**
       * ... Handle events on error
       */
      const { error } = event.detail;
      setIsSubmitting(false);
      setErrorMessage(error.message);
      console.error('There was an error', error);
    };

    // STEP #9: Add an event listener to get input focus status
    const onFocus = (_event) => {
      setInputErrorMessage(''); // Example: clear input error message
    };

    // STEP #10: Add an event listener to show input error message when finish typing
    const onBlur = (event) => {
      const { error } = event.detail;
      setInputErrorMessage(error?.message ?? JSON.stringify(error)); // Example: set input error message
    };

    const domElement = document.getElementById('card');
    domElement.addEventListener('onReady', onReady);
    domElement.addEventListener('onError', onError);
    domElement.addEventListener('onBlur', onBlur);
    domElement.addEventListener('onFocus', onFocus);
    return () => {
      domElement.removeEventListener('onReady', onReady);
      domElement.removeEventListener('onError', onError);
      domElement.removeEventListener('onFocus', onFocus);
      domElement.removeEventListener('onBlur', onBlur);
    };
  }, []); // This effect should ONLY RUN ONCE as we do not want to reload Airwallex and remount the elements

  // STEP #6a: Add a button handler to trigger the payment request
  const onTriggerConfirm = () => {
    setIsSubmitting(true); // Example: sets loading state
    setErrorMessage(''); // Example: reset error message
    const card = getElement('card');
    confirmPaymentIntent({
      element: card,
      id: intent_id,
      client_secret,
    })
      // STEP #6b: Listen to the request success response
      .then((response) => {
        /**
         * ...Handle confirm response
         */
        setIsSubmitting(false); // Example: sets loading state
        window.alert(`Payment Intent confirmation was successful: ${JSON.stringify(response)}`);
      })
      // STEP #6c: Listen to the request failure response
      .catch((error) => {
        /**
         * ... Handle error response
         */
        setIsSubmitting(false); // Example: sets loading state
        setErrorMessage(error.message ?? JSON.stringify(error)); // Example: set error message
        console.error('There was an error', error);
      });
  };

  const inputStyle = {
    // Custom styling for the inputs, can be placed in css
    border: '1px solid',
    borderRadius: '5px',
    padding: '5px 10px',
    marginTop: '8px',
    height: '28px',
  };

  return (
    <div>
      <h2>Card integration</h2>
      {/* Example below: show loading state */}
      {!elementShow && <p>Loading...</p>}
      {/* Example below: display response message block */}
      {errorMessage.length > 0 && <p id="error">{errorMessage}</p>}
      <div
        className="field-container"
        style={{ display: elementShow ? 'block' : 'none' }} // Example: Custom styling to only show card when it is mounted
      >
        {/**
         * STEP #3a: Add an empty container for the card element to be placed into
         * - Ensure this is the only element in your document with this id,
         *   otherwise the element may fail to mount.
         */}
        <div
          id="card"
          style={inputStyle} // Example: input styling can be moved to css
        />
        <p style={{ color: 'red' }}>{inputErrorMessage}</p>
        {/* STEP #3b: Add a submit button to trigger the payment request */}
        <button
          onClick={onTriggerConfirm}
          disabled={isSubmitting} // Example: disables button when submitting to prevent resubmission
        >
          Submit
        </button>
      </div>
    </div>
  );
};

export default Card;
