// integrations/react/src/components/Redirect.jsx
/**
 * Redirect.jsx
 * Airwallex Payment Demo - React.  Created by Josie Ku.
 *
 * airwallex-payment-elements Redirect element integration in React.js
 * Comments with "Example" demonstrate how states can be integrated
 * with the element, they can be removed.
 *
 * Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/redirect.md
 */

import React, { useEffect, useState } from 'react';
// STEP #1: At the start of your file, import airwallex-payment-elements package
import { loadAirwallex, createElement } from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

// Enter your Payment Method here, this is used to redirect the customer to the appropriate payment method
// Methods: 'alipaycn', 'alipayhk' , 'gcash' , 'dana', 'kakaopay' , 'tng'
const redirect_method = 'replace-with-your-redirect-method';

const Redirect = () => {
  const [elementShow, setElementShow] = useState(false); // Example: set loading state for element
  const [errorMessage, setErrorMessage] = useState(false); // Example: set error state

  useEffect(() => {
    // STEP #2: Initialize Airwallex on mount with the appropriate production environment and other configurations
    loadAirwallex({
      env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
      origin: window.location.origin, // Setup your event target to receive the browser events message
    }).then(() => {
      // STEP #4: Create the redirect card element
      const redirect = createElement('redirect', {
        intent: {
          // Required, must provide intent details to prepare redirect element for checkout
          id: intent_id,
          client_secret,
        },
        method: redirect_method, // Required, must provide payment method type
      });
      // STEP #5: Mount the element to the empty container created previously
      redirect.mount('redirect'); // This 'redirect' id MUST MATCH the id on your empty container created in Step 3
    });

    // STEP #6: Add an event listener to handle events when the element is mounted
    const onReady = (event) => {
      /**
       * ... Handle event on element mount
       */
      setElementShow(true); // Example: show element when mounted
      console.log(`Element ready, ${JSON.stringify(event.detail)}`);
    };

    // STEP #7: Add an event listener to handle events when the payment is successful
    const onSuccess = (event) => {
      /**
       * ... Handle event on success
       */
      console.log(`Confirm success with ${JSON.stringify(event.detail)}`);
    };

    // STEP #8: Add an event listener to handle events when the payment procedure has failed
    const onError = (event) => {
      /**
       * ... Handle event on error
       */
      const { error } = event.detail;
      setErrorMessage(error.message);
      console.error('There was an error', error);
    };

    window.addEventListener('onReady', onReady);
    window.addEventListener('onSuccess', onSuccess);
    window.addEventListener('onError', onError);
    return () => {
      window.removeEventListener('onReady', onReady);
      window.removeEventListener('onSuccess', onSuccess);
      window.removeEventListener('onError', onError);
    };
  }, []); // This effect should ONLY RUN ONCE as we do not want to reload Airwallex and remount the elements

  // Example: Custom styling for the redirect container, can be placed in css
  const containerStyle = {
    width: '540px',
    margin: '48px auto',
  };

  return (
    <div>
      <h2>Redirect element integration</h2>
      {/* Example below: show loading state */}
      {!elementShow && <p>Loading...</p>}
      {/* Example below: display response message block */}
      {errorMessage.length > 0 && <p id="error">{errorMessage}</p>}
      {/**
       * STEP #3: Add an empty container for the redirect element to be placed into
       * - Ensure this is the only element in your document with this id,
       *   otherwise the element may fail to mount.
       */}
      <div
        id="redirect"
        style={{
          ...containerStyle, // Example: container styling can be moved to css
          display: elementShow ? 'block' : 'none', // Example: only show element when mounted
        }}
      ></div>
    </div>
  );
};

export default Redirect;

// integrations/angular/src/app/redirect/redirect.component.ts
/**
 * redirect.component.ts
 * Airwallex Payment Demo - Angular.  Created by Roy Yang and Josie Ku.
 *
 * airwallex-payment-elements Redirect element integration in Angular
 * Comments with "Example" demonstrate how states can be integrated
 * with the element, they can be removed.
 *
 * Detailed guidance here: https://github.com/airwallex/airwallex-payment-demo/blob/master/docs/redirect.md
 */

import { Component, OnInit } from '@angular/core';
// STEP #1: At the start of your file, import airwallex-payment-elements package
import {
  createElement,
  loadAirwallex,
  ElementType,
  PaymentMethodWithRedirect,
} from 'airwallex-payment-elements';

// Enter your Payment Intent secret keys here
// More on getting these secrets: https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/Intro
const intent_id = 'replace-with-your-intent-id';
const client_secret = 'replace-with-your-client-secret';

// Enter your Payment Method here, this is used to redirect the customer to the appropriate payment method
// Methods: 'alipaycn', 'alipayhk' , 'gcash' , 'dana', 'kakaopay' , 'tng'
const redirect_method = 'replace-with-your-redirect-method' as PaymentMethodWithRedirect;

@Component({
  selector: 'app-redirect',
  templateUrl: './redirect.component.html',
  styles: ['#redirect { width: 540px; margin: 48px auto; }'], // Custom styling for the redirect container
})
export class RedirectComponent implements OnInit {
  loading: boolean; // Example: set loading state
  errorMessage: string; // Example: set error state
  constructor() {
    this.loading = true;
    this.errorMessage = '';
    this.onReady = this.onReady.bind(this);
    this.onSuccess = this.onSuccess.bind(this);
    this.onError = this.onError.bind(this);
  }

  ngOnInit(): void {
    // STEP #2: Initialize Airwallex on mount with the appropriate production environment and other configurations
    loadAirwallex({
      env: 'demo', // Can choose other production environments, 'staging | 'demo' | 'prod'
      origin: window.location.origin, // Setup your event target to receive the browser events message
    }).then(() => {
      // STEP #4, 5: Create and mount the redirect element
      createElement('redirect' as ElementType, {
        intent: {
          // Required, must provide intent details to prepare redirect element for checkout
          id: intent_id,
          client_secret,
        },
        method: redirect_method, // Required, must provide payment method type
      })?.mount('redirect'); // This 'redirect' id MUST MATCH the id on your empty container created in Step 3
    });

    window.addEventListener('onReady', this.onReady);
    window.addEventListener('onSuccess', this.onSuccess);
    window.addEventListener('onError', this.onError);
  }

  // STEP #6: Add an event listener to handle events when the element is mounted
  onReady = (event: any): void => {
    /**
     * ... Handle event on element mount
     */
    this.loading = false; // Example: hide loading state
    console.log(`Element ready, ${JSON.stringify(event.detail)}`);
  };

  // STEP #7: Add an event listener to handle events when the payment is successful
  onSuccess = (event: any): void => {
    /**
     * ... Handle event on success
     */
    window.alert(`Confirm success with ${JSON.stringify(event.detail)}`);
  };

  // STEP #8: Add an event listener to handle events when the payment procedure has failed
  onError = (event: any): void => {
    /**
     * ... Handle event on error
     */
    const { error } = event.detail;
    this.errorMessage = error.message ?? JSON.stringify(error); // Example: set error message
    console.error('There was an error', error);
  };

  OnDestroy(): void {
    window.removeEventListener('onReady', this.onReady);
    window.removeEventListener('onSuccess', this.onSuccess);
    window.removeEventListener('onError', this.onError);
  }
}

<!-- 
  redirect.component.html
  Airwallex Payment Demo - Angular.  Created by Josie Ku.

  This file is the html template for the Redirect component.
 -->
<div>
  <h2>Redirect element integration</h2>
  <!-- Styling example below: show loading state -->
  <p [style.display]="this.loading ? 'block' : 'none'">Loading...</p>
  <!-- Styling example below: show error message -->
  <p
    id="error"
    [style.display]="this.errorMessage.length > 0 ? 'block' : 'none'"
  >
    {{ errorMessage }}
  </p>
  <!-- 
    STEP #3: Add an empty container for the redirect element to be placed into
    - Ensure this is the only element in your document with this id, otherwise 
      the element may fail to mount. 
  -->
  <div [style.display]="!this.loading ? 'block' : 'none'" id="redirect"></div>
</div>
