// angular/src/app/hpp/hpp.component.ts
import { Component, OnInit } from "@angular/core";
import { redirectToCheckout, loadAirwallex } from "airwallex-payment-elements";

const intentid = "replace-with-your-intent-id";
const client_secret = "replace-with-your-client-secret";

@Component({
  selector: "app-hpp",
  templateUrl: "./hpp.component.html",
})
export class HppComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  redirectHpp = async () => {
    try {
      await loadAirwallex({
        env: "staging",
      });
      await redirectToCheckout({
        env: "staging",
        id: intentid,
        client_secret: client_secret,
      });
    } catch (error) {
      // handle errors here
    }
  };
}

<div>
  <h2>Option #1: Hosted payment page (HPP) integration</h2>
  <button on-click="redirectHpp()">Redirect to HPP</button>
</div>

// react/src/components/Hpp.jsx
import React from "react";
import { redirectToCheckout, loadAirwallex } from "airwallex-payment-elements";

const intentid = "replace-with-your-intent-id";
const client_secret = "replace-with-your-client-secret";

const Hpp = () => {
  const redirectHpp = async () => {
    try {
      await loadAirwallex({
        env: "staging",
      });
      await redirectToCheckout({
        env: "staging",
        id: intentid,
        client_secret: client_secret,
      });
    } catch (error) {
      // handle errors here
    }
  };

  return (
    <div>
      <h2>Option #1: Hosted payment page (HPP) integration</h2>
      <button onClick={redirectHpp}>Redirect to HPP</button>
    </div>
  );
};

export default Hpp;
